-- ═══════════════════════════════════════════════════════════
-- ALIGN MVP — Supabase SQL Schema
-- Run this in Supabase Dashboard → SQL Editor
-- ═══════════════════════════════════════════════════════════

-- ── 1. Profiles Table ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profiles (
  id               UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email            TEXT NOT NULL,
  display_name     TEXT,
  total_sessions   INTEGER DEFAULT 0,
  avg_score        INTEGER,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ── 2. Posture Sessions Table ─────────────────────────────────
CREATE TABLE IF NOT EXISTS posture_sessions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  score            INTEGER CHECK (score >= 0 AND score <= 100),   -- KPI: posture score
  good_pct         INTEGER CHECK (good_pct >= 0 AND good_pct <= 100), -- KPI: good frame %
  spine_deg        DECIMAL(5,2),     -- spine tilt degrees
  neck_deg         DECIMAL(5,2),     -- neck angle degrees
  duration_sec     INTEGER,          -- session length in seconds
  feedback_thumb   TEXT CHECK (feedback_thumb IN ('up','down','helpful','not_helpful','see_doctor')),
  ai_recs          JSONB,            -- AI recommendations JSON
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3. Indexes ───────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON posture_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_created_at ON posture_sessions(created_at DESC);

-- ── 4. Row Level Security ─────────────────────────────────────
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE posture_sessions ENABLE ROW LEVEL SECURITY;

-- Profiles: users can only read/update their own profile
CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE USING (auth.uid() = id);

-- Sessions: users can only access their own sessions
CREATE POLICY "Users can insert own sessions"
  ON posture_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own sessions"
  ON posture_sessions FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own sessions"
  ON posture_sessions FOR UPDATE USING (auth.uid() = user_id);

-- Backend service role bypasses RLS automatically — no extra policy needed

-- ── 5. Auto-create profile on signup (trigger) ────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1))
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── 6. Updated_at auto-update ─────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
